apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: k8s.deploywithme.xyz
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://novara-kops-state-production/k8s.deploywithme.xyz
  dnsZone: Z0635472JB9HTR5BRWIR
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1a
      name: a
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1b
      name: b
    - encryptedVolume: true
      instanceGroup: control-plane-us-east-1c
      name: c
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.28.0
  networkCIDR: 10.0.0.0/16
  networkID: vpc-00a927d9838acaa1d
  networking:
    calico: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - id: subnet-0297277c4a8d61321
    name: us-east-1a
    type: Private
    zone: us-east-1a
    egress: nat-049f86ecedf164306
  - id: subnet-08060c23cc8ccba18
    name: us-east-1b
    type: Private
    zone: us-east-1b
    egress: nat-0957d467f232e3889
  - id: subnet-02d5decbe09198b1a
    name: us-east-1c
    type: Private
    zone: us-east-1c
    egress: nat-0c7a98e82452d02e1
  - id: subnet-0d842139591dd97f9
    name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
  - id: subnet-0b362eaf8cdd5b63f
    name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
  - id: subnet-015c045f6747b9956
    name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
  topology:
    masters: private
    nodes: private
    dns:
      type: Public
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.deploywithme.xyz
  name: control-plane-us-east-1a
spec:
  image: ami-05e86b3611c60b0b4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.deploywithme.xyz
  name: control-plane-us-east-1b
spec:
  image: ami-05e86b3611c60b0b4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1b
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.deploywithme.xyz
  name: control-plane-us-east-1c
spec:
  image: ami-05e86b3611c60b0b4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - us-east-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.deploywithme.xyz
  name: nodes-us-east-1a
spec:
  image: ami-05e86b3611c60b0b4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.deploywithme.xyz
  name: nodes-us-east-1b
spec:
  image: ami-05e86b3611c60b0b4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1b
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: k8s.deploywithme.xyz
  name: nodes-us-east-1c
spec:
  image: ami-05e86b3611c60b0b4
  machineType: t3.medium
  maxSize: 1
  minSize: 1
  role: Node
  subnets:
  - us-east-1c
