---
- name: Restart auditd
  systemd:
    name: auditd
    state: restarted

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Restart unattended-upgrades
  systemd:
    name: unattended-upgrades
    state: restarted

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
