apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
  namespace: taskapp
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "taskapp"
  DATABASE_USER: "taskapp"
  APP_ENV: "production"
  FRONTEND_URL: "https://taskapp.deploywithme.xyz"
  BACKEND_PORT: "5000"
