name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=novara-tfstate-745914010393" \
            -backend-config="key=capstone/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -reconfigure
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v3

      - name: Run tflint
        run: |
          tflint --init
          tflint --recursive
        working-directory: terraform

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform

  kubernetes:
    name: Kubernetes Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Validate Kubernetes manifests
        run: |
          if [ -d "k8s/base" ] && [ "$(ls -A k8s/base)" ]; then
            kubectl apply --dry-run=client --validate=false -f k8s/base/
          else
            echo "No manifests found yet — skipping"
          fi

  ansible:
    name: Ansible Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          if [ -d "ansible" ] && [ "$(ls -A ansible)" ]; then
            ansible-lint ansible/
          else
            echo "No ansible files found yet — skipping"
          fi
